'use client'
import { useState, type ChangeEvent } from 'react'
import { ImageIcon, LoaderCircle, Plus, Trash2, Upload } from 'lucide-react'
import { toast } from 'sonner'
import { sectionData } from '../section-defaults'
import type { HomepageSection, HomepageSettings } from '../types'

const input = 'w-full rounded-md border border-input bg-background px-3 py-2 text-sm'
const labelClass = 'mb-1 block text-sm font-medium'

export function HomepageEditor({ initial }: { initial: HomepageSettings }) {
  const [doc, setDoc] = useState(initial.draft)
  const [tab, setTab] = useState<'content'|'seo'|'code'>('content')
  const [busy, setBusy] = useState(false)
  const updateSection = (index: number, section: HomepageSection) => setDoc(v => ({ ...v, sections: v.sections.map((s,i) => i === index ? section : s) }))
  async function save(url: string, method: 'PATCH'|'POST') {
    setBusy(true)
    try { const response = await fetch(url,{method,headers:{'Content-Type':'application/json'},body:JSON.stringify(doc)}); if(!response.ok) throw new Error(); toast.success(method==='POST'?'Homepage publicada':'Borrador guardado') }
    catch { toast.error('No se pudo completar la operación') } finally { setBusy(false) }
  }
  return <div className="space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="text-2xl font-bold">Homepage</h1><p className="text-sm text-muted-foreground">Cada sección conserva el diseño y la cantidad de elementos del sitio.</p></div><div className="flex flex-wrap gap-2"><a href="/" target="_blank" className="rounded-md border px-4 py-2 text-sm">Ver publicada</a><button disabled={busy} onClick={()=>save('/api/admin/homepage','PATCH')} className="rounded-md border px-4 py-2 text-sm">Guardar borrador</button><button disabled={busy} onClick={()=>save('/api/admin/homepage/publish','POST')} className="rounded-md bg-primary px-4 py-2 text-sm text-primary-foreground">Publicar</button></div></div>
    <div className="flex gap-2 border-b">{(['content','seo','code'] as const).map(t=><button key={t} onClick={()=>setTab(t)} className={`px-4 py-2 text-sm ${tab===t?'border-b-2 border-primary font-semibold':''}`}>{t==='content'?'Secciones':t==='seo'?'SEO y Schema':'Head y Body'}</button>)}</div>
    {tab==='content' && <div className="space-y-4">{doc.sections.map((section,index)=><SectionEditor key={section.id} section={section} onChange={value=>updateSection(index,value)}/>)}</div>}
    {tab==='seo' && <div className="grid gap-4 rounded-lg border bg-card p-5 md:grid-cols-2"><Text label="Título SEO" value={doc.seo.title} onChange={title=>setDoc(v=>({...v,seo:{...v.seo,title}}))}/><Area label="Meta descripción" value={doc.seo.description} onChange={description=>setDoc(v=>({...v,seo:{...v.seo,description}}))}/><Text label="URL canónica" value={doc.seo.canonicalUrl} onChange={canonicalUrl=>setDoc(v=>({...v,seo:{...v.seo,canonicalUrl}}))}/><Text label="Robots" value={doc.seo.robots} onChange={robots=>setDoc(v=>({...v,seo:{...v.seo,robots}}))}/><Text label="Open Graph: título" value={doc.seo.ogTitle} onChange={ogTitle=>setDoc(v=>({...v,seo:{...v.seo,ogTitle}}))}/><ImageUpload label="Open Graph: imagen" value={doc.seo.ogImage} onChange={ogImage=>setDoc(v=>({...v,seo:{...v.seo,ogImage}}))}/><label className="md:col-span-2"><span className={labelClass}>Schema JSON-LD</span><textarea className={`${input} font-mono`} rows={12} value={JSON.stringify(doc.seo.schemaJsonLd??{},null,2)} onChange={e=>{try{const schemaJsonLd=JSON.parse(e.target.value);setDoc(v=>({...v,seo:{...v.seo,schemaJsonLd}}))}catch{}}}/></label></div>}
    {tab==='code' && <div className="space-y-4 rounded-lg border bg-card p-5"><div className="rounded-md border border-amber-300 bg-amber-50 p-3 text-sm text-amber-900">Código avanzado. Usa solamente etiquetas de proveedores confiables.</div>{([['headHtml','Antes de cerrar </head>'],['bodyStartHtml','Al inicio de <body>'],['bodyEndHtml','Antes de cerrar </body>']] as const).map(([key,title])=><Area key={key} label={title} value={doc.integrations[key]} rows={8} onChange={value=>setDoc(v=>({...v,integrations:{...v.integrations,[key]:value}}))}/>)}</div>}
  </div>
}

function SectionEditor({section,onChange}:{section:HomepageSection;onChange:(section:HomepageSection)=>void}) {
  const data = sectionData(section.id,section.data)
  const set = (key:string,value:unknown)=>onChange({...section,data:{...data,[key]:value}})
  const fields=(names:FieldDef[]) => <div className="grid gap-4 md:grid-cols-2">{names.map(([key,label,type='text'])=>type==='image'?<ImageUpload key={key} label={label} value={String(data[key]??'')} onChange={v=>set(key,v)}/>:type==='area'?<Area key={key} label={label} value={String(data[key]??'')} onChange={v=>set(key,v)}/>:<Text key={key} label={label} value={String(data[key]??'')} onChange={v=>set(key,v)}/>)}</div>
  let editor: React.ReactNode
  if(section.id==='hero') editor=fields([['title','Primera línea'],['titleAccent','Línea destacada'],['subtitle','Subtítulo','area'],['imageUrl','Imagen de fondo','image'],['imageAlt','Texto alternativo']])
  else if(section.id==='awards') editor=<>{fields([['title','Título'],['iconUrl','Ícono de los reconocimientos','image']])}<ObjectList title="Reconocimientos" itemName="reconocimiento" items={data.items} keys={[['eyebrow','Encabezado'],['title','Reconocimiento'],['detail','Detalle']]} onChange={v=>set('items',v)}/></>
  else if(section.id==='properties') editor=fields([['title','Primera parte del título'],['titleAccent','Parte destacada'],['subtitle','Subtítulo','area'],['buttonLabel','Texto del enlace'],['buttonUrl','Destino del enlace']])
  else if(section.id==='about') editor=fields([['title','Primera parte del título'],['titleAccent','Parte destacada'],['lead','Texto destacado'],['paragraph1','Primer párrafo','area'],['paragraph2','Segundo párrafo','area'],['coachingText','Texto KW MAPS','area'],['imageUrl','Imagen principal','image'],['imageAlt','Texto alternativo'],['overlayTitle','Título sobre imagen'],['overlaySubtitle','Subtítulo sobre imagen']])
  else if(section.id==='join') editor=<>{fields([['headerImageUrl','Imagen de encabezado','image'],['headerImageAlt','Texto alternativo']])}<ObjectList title="2 tarjetas" items={data.cards} keys={[['title','Título'],['copy','Descripción'],['href','Enlace'],['imageUrl','Imagen','image'],['buttonLabel','Texto del enlace']]} fixed={2} onChange={v=>set('cards',v)}/></>
  else if(section.id==='family') editor=<>{fields([['eyebrow','Antetítulo'],['title','Título'],['lead','Texto destacado','area'],['body','Descripción','area'],['buttonLabel','Texto del botón'],['buttonUrl','Enlace del botón'],['videoUrl','URL embed de YouTube']])}<ObjectList title="4 métricas" items={data.metrics} keys={[['value','Valor'],['label','Etiqueta']]} fixed={4} onChange={v=>set('metrics',v)}/></>
  else if(section.id==='allies') editor=<>{fields([['title','Primera parte del título'],['titleAccent','Parte destacada'],['titleSuffix','Última parte'],['subtitle','Descripción','area']])}<ImageList title="Logos de aliados" items={data.logos} onChange={v=>set('logos',v)}/></>
  else if(section.id==='allies-info') editor=<>{fields([['title','Título del primer bloque'],['prompt','Pregunta destacada'],['image1Url','Imagen del primer bloque','image'],['image1Alt','Texto alternativo'],['secondTitle','Título del segundo bloque'],['secondLead','Texto destacado'],['image2Url','Imagen del segundo bloque','image'],['image2Alt','Texto alternativo'],['buttonLabel','Texto del botón'],['buttonUrl','Enlace del botón']])}<StringList title="2 párrafos del primer bloque" items={data.paragraphs} fixed={2} onChange={v=>set('paragraphs',v)}/><StringList title="2 párrafos del segundo bloque" items={data.secondParagraphs} fixed={2} onChange={v=>set('secondParagraphs',v)}/></>
  else if(section.id==='prospecting') editor=fields([['eyebrow','Antetítulo'],['title','Título accesible'],['body','Descripción','area'],['imageUrl','Ilustración','image'],['imageAlt','Texto alternativo'],['buttonLabel','Texto del botón'],['buttonUrl','Enlace del botón']])
  else editor=fields([['title','Título'],['description','Descripción','area'],['email','Correo'],['phone','Teléfono visible'],['phoneUrl','Teléfono para enlace'],['address','Dirección','area'],['hours','Horario'],['mapUrl','URL embed de Google Maps','area']])
  return <section className="rounded-lg border bg-card p-5"><div className="mb-5 flex items-center justify-between"><div><h2 className="font-semibold">{section.label}</h2><p className="text-xs text-muted-foreground">{section.id}</p></div><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={section.visible} onChange={e=>onChange({...section,visible:e.target.checked})}/> Visible</label></div>{editor}</section>
}

type FieldDef = [string, string, type?: 'text'|'area'|'image']
type KeyDef = [string, string, type?: 'text'|'image']
function ObjectList({title,items,keys,fixed,itemName='elemento',onChange}:{title:string;items:unknown;keys:KeyDef[];fixed?:number;itemName?:string;onChange:(v:Record<string,string>[])=>void}) { const list=Array.isArray(items)?items as Record<string,string>[]:[]; const normalized=fixed===undefined?list:Array.from({length:fixed},(_,i)=>list[i]??{}); const dynamic=fixed===undefined; return <div className="mt-5"><div className="mb-3 flex items-center justify-between gap-3"><h3 className="text-sm font-semibold">{title} ({normalized.length})</h3>{dynamic&&<button type="button" onClick={()=>onChange([...normalized,{}])} className="inline-flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><Plus className="size-4"/> Añadir</button>}</div>{normalized.length===0?<p className="rounded-md border border-dashed p-4 text-sm text-muted-foreground">No hay {title.toLowerCase()}.</p>:<div className="grid gap-4 lg:grid-cols-2">{normalized.map((item,i)=><div key={i} className="space-y-3 rounded-md border p-4"><div className="flex items-center justify-between gap-3"><p className="text-xs font-bold text-muted-foreground">{itemName.charAt(0).toUpperCase()+itemName.slice(1)} {i+1}</p>{dynamic&&<button type="button" aria-label={`Eliminar ${itemName} ${i+1}`} onClick={()=>onChange(normalized.filter((_,j)=>j!==i))} className="inline-flex items-center gap-1 rounded-md border border-destructive/30 px-2 py-1 text-xs text-destructive"><Trash2 className="size-3.5"/> Eliminar</button>}</div>{keys.map(([key,label,type])=>type==='image'?<ImageUpload key={key} label={label} value={item[key]} onChange={v=>onChange(normalized.map((x,j)=>j===i?{...x,[key]:v}:x))}/>:<Text key={key} label={label} value={item[key]} onChange={v=>onChange(normalized.map((x,j)=>j===i?{...x,[key]:v}:x))}/>)}</div>)}</div>}</div> }
function StringList({title,items,fixed,onChange}:{title:string;items:unknown;fixed:number;onChange:(v:string[])=>void}) { const list=Array.isArray(items)?items.map(String):[]; const normalized=Array.from({length:fixed},(_,i)=>list[i]??''); return <div className="mt-5 space-y-3"><h3 className="text-sm font-semibold">{title}</h3>{normalized.map((value,i)=><Area key={i} label={`Párrafo ${i+1}`} value={value} onChange={v=>onChange(normalized.map((x,j)=>j===i?v:x))}/>)}</div> }
function ImageList({title,items,onChange}:{title:string;items:unknown;onChange:(v:string[])=>void}) { const list=Array.isArray(items)?items.map(String):[]; return <div className="mt-5"><div className="mb-3 flex items-center justify-between gap-3"><h3 className="text-sm font-semibold">{title} ({list.length})</h3><button type="button" onClick={()=>onChange([...list,''])} className="inline-flex items-center gap-2 rounded-md border px-3 py-2 text-sm"><Plus className="size-4"/> Añadir</button></div>{list.length===0?<p className="rounded-md border border-dashed p-4 text-sm text-muted-foreground">No hay logos de aliados.</p>:<div className="grid gap-4 md:grid-cols-2">{list.map((value,i)=><div key={i} className="space-y-2 rounded-md border p-4"><div className="flex justify-end"><button type="button" aria-label={`Eliminar logo ${i+1}`} onClick={()=>onChange(list.filter((_,j)=>j!==i))} className="inline-flex items-center gap-1 rounded-md border border-destructive/30 px-2 py-1 text-xs text-destructive"><Trash2 className="size-3.5"/> Eliminar</button></div><ImageUpload label={`Logo ${i+1}`} value={value} onChange={v=>onChange(list.map((x,j)=>j===i?v:x))}/></div>)}</div>}</div> }
function Text({label,value,onChange}:{label:string;value?:string;onChange:(v:string)=>void}) { return <label><span className={labelClass}>{label}</span><input className={input} value={value??''} onChange={e=>onChange(e.target.value)}/></label> }
function Area({label,value,onChange,rows=3}:{label:string;value?:string;onChange:(v:string)=>void;rows?:number}) { return <label className="md:col-span-2"><span className={labelClass}>{label}</span><textarea className={input} rows={rows} value={value??''} onChange={e=>onChange(e.target.value)}/></label> }
function ImageUpload({label,value,onChange}:{label:string;value?:string;onChange:(v:string)=>void}) { const [uploading,setUploading]=useState(false); async function upload(e:ChangeEvent<HTMLInputElement>){const file=e.target.files?.[0];e.target.value='';if(!file)return;if(file.size>8*1024*1024)return toast.error('Máximo 8 MB');setUploading(true);try{const body=new FormData();body.set('image',file);const response=await fetch('/api/admin/homepage/images',{method:'POST',body});if(!response.ok)throw new Error();onChange((await response.json()).url);toast.success('Imagen subida')}catch{toast.error('No se pudo subir')}finally{setUploading(false)}} return <div><span className={labelClass}>{label}</span><div className="flex gap-3 rounded-md border p-3">{value?<img src={value} alt="Vista previa" className="size-20 rounded object-contain"/>:<div className="flex size-20 items-center justify-center bg-muted"><ImageIcon/></div>}<div className="min-w-0 flex-1 space-y-2"><label className="inline-flex cursor-pointer items-center gap-2 rounded border px-3 py-2 text-sm">{uploading?<LoaderCircle className="size-4 animate-spin"/>:<Upload className="size-4"/>} Subir<input type="file" accept="image/jpeg,image/png,image/webp,image/gif" className="sr-only" onChange={upload}/></label><input className={input} value={value??''} placeholder="URL de imagen" onChange={e=>onChange(e.target.value)}/></div></div></div> }
