export const sectionDefaults: Record<string, Record<string, unknown>> = {
  hero: { title: 'Encuentra la casa de', titleAccent: 'tus sueños', subtitle: 'El camino a tu nuevo hogar empieza aquí con los expertos.', imageUrl: '/Fondo_New_Natural.png', imageAlt: 'Residencia contemporánea con alberca' },
  awards: {
    title: 'Reconocimientos internacionales', iconUrl: '/award-icon.png',
    items: [
      { eyebrow: 'KW Worldwide', title: '#1 Growth Share', detail: 'A nivel mundial (2024)' }, { eyebrow: 'KW Worldwide', title: '#1 Unidades cerradas', detail: 'A nivel mundial (2024)' },
      { eyebrow: 'KW Worldwide', title: '#1 Comisiones brutas', detail: 'A nivel mundial (2024)' }, { eyebrow: 'Presidents Award por KWW', title: 'Región con más Market Centers', detail: 'Aperturados (2024)' },
      { eyebrow: 'Mejor oficina inmobiliaria noroeste', title: 'KW Regio', detail: '2019' }, { eyebrow: 'Mujer inmobiliaria del año', title: 'Bárbara Gaxoét', detail: '2019' },
      { eyebrow: 'Mejor franquicia inmobiliaria', title: 'KW México', detail: '2018' }, { eyebrow: 'Premio al ícono inmobiliario', title: 'Jorge Carbonell / CEO KW México', detail: '2017' },
    ],
  },
  properties: { title: 'Propiedades cerca de ti', buttonLabel: 'Ver más...', buttonUrl: '/propiedades' },
  about: { title: '¿QUÉ ES', titleAccent: 'KW?', lead: 'EMPRESA NÚMERO 1 DE ENTRENAMIENTO', paragraph1: 'networking, aprendizaje y coaching para agentes inmobiliarios.', paragraph2: 'Construye un negocio, no solo un empleo. Usa nuestros entrenamientos, sistemas y modelos probados.', coachingText: 'Programas de entrenamiento para potencializar tu negocio.', imageUrl: '/section-banner-image.png', imageAlt: 'Profesionales inmobiliarios colaborando en una sesión de entrenamiento', overlayTitle: 'Mentalidad de millonario', overlaySubtitle: 'Modelos probados desde 1983' },
  join: { headerImageUrl: '/section-joinus-image-2.png', headerImageAlt: 'Únete a KW', cards: [{ title: 'Únete a la familia KW', copy: 'Impulsa tu carrera con capacitación, tecnología y una comunidad que crece contigo.', href: 'https://kwmx.mx/unete-a-kw-620406', imageUrl: '/Join-us-1.png', buttonLabel: 'Conocer más' }, { title: 'Invierte en una franquicia', copy: 'Lidera un Market Center y transforma el mercado inmobiliario de tu ciudad.', href: 'https://kwmx.mx/franquicias', imageUrl: '/Join-us-2.png', buttonLabel: 'Conocer más' }] },
  family: { eyebrow: 'El evento de nuestra comunidad', title: 'Family Reunion', lead: 'Tres días de entrenamiento, networking, aprendizaje y coaching para agentes inmobiliarios.', body: 'Cada año reunimos las mejores prácticas del sector para llevar los negocios de nuestra comunidad al siguiente nivel.', metrics: [{ value: '11', label: 'Años creando historias' }, { value: '+10K', label: 'Asistentes' }, { value: '+3K', label: 'Horas de entrenamiento' }, { value: '+200%', label: 'Productividad' }], buttonLabel: 'Pre - Registro Family Reunion 2027', buttonUrl: 'https://kwfamilyreunion.mx/', videoUrl: 'https://www.youtube.com/embed/Au3Py1qH75o?start=2' },
  allies: { title: 'Aliados', titleAccent: 'KW', titleSuffix: 'México', subtitle: 'Conecta con la red inmobiliaria más grande de México. Nuestros aliados son fundamentales para el ecosistema KW.', logos: ['/Ally-slider-1.png','/Ally-slider-2.png','/Ally-slider-3.png','/Ally-slider-5.png','/Ally-slider-6.png','/Ally-slider7.png','/Ally-slider-8.png','/Ally-slider-9.png','/Ally-slider-10.png','/Ally-slider-11.png'] },
  'allies-info': { title: 'Conecta con la red inmobiliaria más grande de México', paragraphs: ['KW México reúne a más de 2,000 agentes inmobiliarios activos distribuidos en Market Centers a lo largo del país. Al convertirte en aliado, tu marca llega directamente a profesionales con alto poder de decisión y a sus clientes: compradores, vendedores e inversionistas del mercado inmobiliario mexicano.','Nuestros aliados tienen presencia en eventos nacionales como Family Reunion, en nuestras plataformas digitales y en la operación diaria de nuestra red.'], prompt: '¿Tu marca quiere estar donde crece el sector inmobiliario?', image1Url: '/Ally-description-1.png', image1Alt: 'Comunidad reunida en un evento profesional', secondTitle: 'Proveedores de servicios', secondLead: 'Sé parte del ecosistema que impulsa a los agentes KW.', secondParagraphs: ['Los agentes KW México necesitan herramientas, servicios y soluciones confiables para operar y crecer su negocio. Si ofreces servicios financieros, legales, tecnológicos, de capacitación o bienestar, hay un lugar para ti en nuestra red.','Como proveedor aliado, accedes a una comunidad profesional en constante crecimiento, con necesidades reales y ciclos de compra activos. Trabajamos con quienes comparten nuestro compromiso con la excelencia y el desarrollo del agente.'], image2Url: '/Ally-description-2.png', image2Alt: 'Profesionales estrechando las manos para cerrar una alianza', buttonLabel: 'Hablemos', buttonUrl: 'mailto:info@kwmexico.mx?subject=Quiero%20ser%20proveedor%20aliado%20KW' },
  prospecting: { eyebrow: 'Tu siguiente oportunidad comienza aquí', title: '¿Listo para prosperar?', body: 'Únete a la red inmobiliaria de mayor crecimiento y transforma tu carrera con el mejor entrenamiento y tecnología del mercado.', imageUrl: '/interseccion.png', imageAlt: '', buttonLabel: 'Comienza tu historia de éxito', buttonUrl: '#contact' },
  contact: { title: 'Contacto', description: 'Nuestro equipo está listo para ayudarte a encontrar la oportunidad adecuada.', email: 'info@kwmexico.mx', phone: '(52) 442 251 2295', phoneUrl: '+524422512295', address: 'Cto. Álamos #83, 3er piso, Álamos 2da Sección, Querétaro, Qro.', hours: 'Lun - Vie · 9:00 - 14:30 y 16:00 - 19:00', mapUrl: 'https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d3734.49900651222!2d-100.38546172565698!3d20.60850740208178!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x85d35b3cf101cde5%3A0xf76875173a8ed9f0!2sKW%20M%C3%A9xico!5e0!3m2!1ses!2smx!4v1778085670264!5m2!1ses!2smx' },
}

export function sectionData(id: string, data?: Record<string, unknown>) {
  return { ...(sectionDefaults[id] ?? {}), ...(data ?? {}) }
}
