import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/src/shared/components/sonner";
import ProviderReactQuery from "@/src/shared/components/ProviderReactQuery";

// Helvetica Neue LT Std con licencia web (archivos entregados por el
// cliente, convertidos a woff2 en src/fonts/helvetica-neue/). Es la
// tipografía única del sitio: cuerpo, encabezados, navbar y toda sección
// usan esta misma familia — el cliente pidió exactamente esta, sin
// alternativas ni sustitutos.
const helveticaNeue = localFont({
  src: [
    { path: "../src/fonts/helvetica-neue/HelveticaNeueLTStd-Light.woff2", weight: "300", style: "normal" },
    { path: "../src/fonts/helvetica-neue/HelveticaNeueLTStd-Roman.woff2", weight: "400", style: "normal" },
    { path: "../src/fonts/helvetica-neue/HelveticaNeueLTStd-Medium.woff2", weight: "500 600", style: "normal" },
    { path: "../src/fonts/helvetica-neue/HelveticaNeueLTStd-Bold.woff2", weight: "700", style: "normal" },
  ],
  variable: "--font-helvetica",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", helveticaNeue.variable)}
    >
      <body className="min-h-full flex flex-col">
        <ProviderReactQuery>
          {children}
        </ProviderReactQuery>
      </body>
    </html>
  );
}
