import type { Metadata } from "next";
import { Rubik, Roboto } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import { Toaster } from "@/src/shared/components/sonner";
import ProviderReactQuery from "@/src/shared/components/ProviderReactQuery";

// Roboto = alternativa web de Helvetica Neue LT Std (cuerpo/texto de apoyo).
// Rubik = alternativa web de DIN Next LT Pro Heavy Condensed (titulares).
// Ambas indicadas por el cliente como fuentes seguras para web cuando las
// tipografías de marca no están disponibles como Google Fonts.
const roboto = Roboto({ subsets: ['latin'], variable: '--font-sans' });
const rubik = Rubik({ subsets: ['latin'], variable: '--font-heading' });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className={cn("h-full", "antialiased", "font-sans", roboto.variable, rubik.variable)}
    >
      <body className="min-h-full flex flex-col">
        <ProviderReactQuery>
          {children}
        </ProviderReactQuery>
      </body>
    </html>
  );
}
